
package com.juliano.cliente;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ExemploService", targetNamespace = "http://juliano.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ExemploService {


    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calcula", targetNamespace = "http://juliano.com/", className = "com.juliano.cliente.Calcula")
    @ResponseWrapper(localName = "calculaResponse", targetNamespace = "http://juliano.com/", className = "com.juliano.cliente.CalculaResponse")
    @Action(input = "http://juliano.com/ExemploService/calculaRequest", output = "http://juliano.com/ExemploService/calculaResponse")
    public int calcula(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "exibeNome", targetNamespace = "http://juliano.com/", className = "com.juliano.cliente.ExibeNome")
    @ResponseWrapper(localName = "exibeNomeResponse", targetNamespace = "http://juliano.com/", className = "com.juliano.cliente.ExibeNomeResponse")
    @Action(input = "http://juliano.com/ExemploService/exibeNomeRequest", output = "http://juliano.com/ExemploService/exibeNomeResponse")
    public String exibeNome(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
